FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    tmux \
    nano \
    htop \

# Force bash color prompt
RUN sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' ~/.bashrc

COPY env.yml /workspace

RUN conda env update --file /workspace/env.yml --name base

RUN ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh \n" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc
SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]


CMD ["/bin/bash"]

